### PR TITLE
Initial python 3 porting done.  Tests pass.

### PR DESCRIPTION
**Pull request by thatch**
I don't have a pi handy to test workflow, but the tests pass.  @brianredbeard or @cunninghamsandwich can you give it a shot?

BTW on a fresh Ubuntu system you should be able to do something like

```
sudo apt-get install python3-evdev
cd /path/to/makerspace-auth/software
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements-test.txt
make test
```

Refs #29

### CODE REVIEW

**Review by brianredbeard — APPROVED** [review]
Everything looks good.  

I found issues with the underlying tests (which are resolved in https://github.com/google/makerspace-auth/commit/1a12966c3e8658c6b29b2ffc91d4a757fc20c09e), but all of the changes work well.

Nose tests were run successfully with Python 3.7.3 and Python 2.7.15
Functional testing succeeded with  Python 3.7.3 and Python 2.7.15 using `two_button.py` and `qa.py`

All tests were run on a Raspberry Pi 3 Model B (a32082)

**Comment by brianredbeard** [comment]
Once this get's merged, I'll then submit a PR with the test fixes so as to avoid the wrath of @googlebot.

In parallel I'm going to rebase #28 against this and then subsequently re-submit.

**Comment by brianredbeard** [comment]
@cunninghamsandwich any oppositions to these changes?

**Review by cunninghamsandwich — APPROVED** [review]
Looks good to me.

**Pull request merged**
