### PR TITLE
Modernize automation

### PR DESCRIPTION
**Pull request by thatch**
1. Enables isort+black+flake8, reformat everything except examples
1. Makes it easy to set up a virtualenv
1. Can run tests on multiple versions locally with tox
1. Enables Github Actions including running lint
1. Speed up tests using FakeTime
1. Add a test for `authbox.timer`

### CODE REVIEW

**Comment by thatch** [comment]
A sample action run is https://github.com/thatch/makerspace-auth/runs/308216183 -- once enabled in the repo it should also show them on pull requests (the term here is "checks", both the box where it would check the CLA and in the tab above)

**Comment by thvortex** [comment]
How should we run test_qa.py and test_two_button.py which are outside of the authbox directory?

**Comment by precision** [comment]
Seems to be a problem w/ the Makefile:

```
pi@arblaser:~/tmp/makerspace-auth/software $ make venv
python3 -m venv .venv
source .venv/bin/activate && make setup
/bin/sh: 1: source: not found
make: *** [Makefile:8: venv] Error 127
pi@arblaser:~/tmp/makerspace-auth/software $ source .venv/bin/activate
(.venv) pi@arblaser:~/tmp/makerspace-auth/software $ make setup
python -m pip install -Ur requirements-dev.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting fake-rpi==0.6.2 (from -r requirements-dev.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5c/83/f24e4452709b0a4cb102919f88c9d92d0efe7b3ebe68e14e2c216921fa82/fake_rpi-0.6.2-py3-none-any.whl
Collecting nose==1.3.7 (from -r requirements-dev.txt (line 2))
...

```

**Comment by thvortex** [comment]
"source" is a bash built-in. Are you using a different shell by chance?

**Comment by precision** [comment]
Nope, this is just a standard raspbian install.

```
(.venv) pi@arblaser:~/tmp/makerspace-auth/software $ echo $SHELL
/bin/bash

```

**Comment by thvortex** [comment]
Ah, Makefile is defaulting to /bin/sh which on Raspbian points to /bin/dash and not /bin/bash. Adding the following line to the top of the Makefile should fix it:
`SHELL=/bin/bash`

**Comment by precision** [comment]
Thanks @thvortex SHELL does fix it, however all the other targets fail unless you've manually sourced .venv/bin/activate before launching make.

This was just a quick hack, seems to work, but for some reason `make test` is complaining about numpy

```
diff --git a/software/Makefile b/software/Makefile
index 71670cf..8187d49 100644
--- a/software/Makefile
+++ b/software/Makefile
@@ -1,32 +1,36 @@
-PYTHON?=python
+.ONESHELL:
+SHELL=/bin/bash
+PYTHON?=python3
 NOSE?=$(PYTHON) -m nose
 SOURCES=authbox setup.py
 
 .PHONY: venv
 venv:
-       $(PYTHON) -m venv .venv
-       source .venv/bin/activate && make setup
-       @echo 'run `source .venv/bin/activate` to use virtualenv'
+       test -d .venv || $(PYTHON) -m venv .venv
 
 # The reset of these are intended to be run within the venv, where python points
 # to whatever was used to set up the venv.
 
-.POHONY: setup
-setup:
+.PHONY: setup
+setup:  venv
+       source .venv/bin/activate
        python -m pip install -Ur requirements-dev.txt
 
 .PHONY: test
-test:
+test: venv
+       source .venv/bin/activate
        python -m coverage run -m authbox.tests $(TESTOPTS)
        python -m coverage report --fail-under=75 --omit='.venv/*,.tox/*' --show-missing
 
 .PHONY: format
-format:
+format: venv
+       source .venv/bin/activate
        python -m isort --recursive -y $(SOURCES)
        python -m black $(SOURCES)
 
 .PHONY: lint
-lint:
+lint: venv
+       source .venv/bin/activate
        python -m isort --recursive --diff $(SOURCES)
        python -m black --check $(SOURCES)
        python -m flake8 $(SOURCES)

```

**Comment by thvortex** [comment]
Ok, I _think_ the problem is that the https://pypi.org/project/numpy/#files repo doesn't seem to have native C extensions compiled for ARM. I was able to make it work outside of a venv with:
```
sudo apt-get install python3-numpy
python3 -m pip install -Ur requirements-dev.txt
python3 -m coverage run -m authbox.tests
python3 -m coverage report --fail-under=75 --include='authbox/*' --show-missing
```

**Comment by precision** [comment]
Seems you also need to install libatlas-base-dev on Raspbian.  Here is a diff that works out of the box.

```
diff --git a/software/Makefile b/software/Makefile
index 71670cf..a8b860c 100644
--- a/software/Makefile
+++ b/software/Makefile
@@ -1,32 +1,37 @@
-PYTHON?=python
+.ONESHELL:
+SHELL=/bin/bash
+PYTHON?=python3
 NOSE?=$(PYTHON) -m nose
 SOURCES=authbox setup.py
 
 .PHONY: venv
 venv:
-       $(PYTHON) -m venv .venv
-       source .venv/bin/activate && make setup
-       @echo 'run `source .venv/bin/activate` to use virtualenv'
+       test -d .venv || $(PYTHON) -m venv .venv
 
 # The reset of these are intended to be run within the venv, where python points
 # to whatever was used to set up the venv.
 
-.POHONY: setup
-setup:
+.PHONY: setup
+setup:  venv
+       source .venv/bin/activate
        python -m pip install -Ur requirements-dev.txt
+       @echo 'If you are running this on Raspbian execute: `sudo apt-get install python3-numpy libatlas-base-dev`'
 
 .PHONY: test
-test:
+test: venv
+       source .venv/bin/activate
        python -m coverage run -m authbox.tests $(TESTOPTS)
        python -m coverage report --fail-under=75 --omit='.venv/*,.tox/*' --show-missing
 
 .PHONY: format
-format:
+format: venv
+       source .venv/bin/activate
        python -m isort --recursive -y $(SOURCES)
        python -m black $(SOURCES)
 
 .PHONY: lint
-lint:
+lint: venv
+       source .venv/bin/activate
        python -m isort --recursive --diff $(SOURCES)
        python -m black --check $(SOURCES)
        python -m flake8 $(SOURCES)
```

**Comment by thatch** [comment]
1. The sample files are included in the `sdist` but not the `bdist` -- I don't have a good idea of what to do with them.  I can move them to a `authbox.contrib.` package but that's less discoverable.  If they're usable without modifications, then including them makes sense.  Thoughts?

2. The `dash` issue is just that it asked you to use `source` instead of `.` right?  It should work when you use `.`

3. The intent (and the docs could be improved here) is that you run make venv, then source the file, and now you're in the venv so it uses the venv python at the head of the path when you run other commands.  Without explicitly adding the `venv` target as a prereq makes it work in tox (which uses its own virtualenv) but also makes it work if you just wanted to `PYTHONPATH=$PWD` and use system python with the deps installed.

4. The default `PYTHON?=python` works on github actions, because when you select a version it gets symlinked to be _the_ `python`.

**Comment by thatch** [comment]
Oh, I see it does use `source` directly, in addition to advising you to.

**Comment by thatch** [comment]
I'm a little confused about the libatlas reference, I'll reflash a pi here.  Any particular version of raspbian you're using?

**Comment by precision** [comment]
Just using the latest [Raspbian Buster Lite](https://www.raspberrypi.org/downloads/raspbian/) version from the Pi foundation.  libatlas-base-dev provides libf77blas.so.3 which python3-numpy depends on. Not sure why it isn't a proper Debian dependency, but it seemingly isn't.

**Comment by thvortex** [comment]
I'm using Raspbian Buster Lite as well. I didn't have to explicitly install libatlas-base-dev though. It was enough just to install python3-numpy, although I had done an apt-get update, dist-upgrade beforehand. Of course, this only fixes things if you run outside of the venv. The only way I could make it work inside venv is to add --system-site-packages when creating it but that kind of defeats the purpose.

**Comment by thvortex** [comment]
Here's what I propose. Since most of the Makefile commands don't need a virtual env when running manually on the command line, let's just remove the "venv" target from the original Makefile @thatch proposed. Tox creates its own venv and doesn't rely on that rule. Creating a venv for development work is then left as an exercise for the reader. A few minor changes:
- Keep `PYTHON?=python` so it works with tox, but use `${PYTHON}` in every make recipe so it's easier to switch b/w python versions outside of a venv.
- Use `--include='authbox/*'` instead of `--omit='.venv/*,.tox/*'` with coverage report. Works equally well outside and inside of a venv. Otherwise you'd have to also omit .local and dist-packages.
- Add `--omit='authbox/tests/*'` in addition to --include so the tests themselves don't inflate coverage percentage.

Proposed diff:
```
diff --git a/software/Makefile b/software/Makefile
index 71670cf..fce0f9e 100644
--- a/software/Makefile
+++ b/software/Makefile
@@ -1,32 +1,22 @@
 PYTHON?=python
-NOSE?=$(PYTHON) -m nose
 SOURCES=authbox setup.py
 
-.PHONY: venv
-venv:
-       $(PYTHON) -m venv .venv
-       source .venv/bin/activate && make setup
-       @echo 'run `source .venv/bin/activate` to use virtualenv'
-
-# The reset of these are intended to be run within the venv, where python points
-# to whatever was used to set up the venv.
-
-.POHONY: setup
+.PHONY: setup
 setup:
-       python -m pip install -Ur requirements-dev.txt
+       ${PYTHON} -m pip install -Ur requirements-dev.txt
 
 .PHONY: test
 test:
-       python -m coverage run -m authbox.tests $(TESTOPTS)
-       python -m coverage report --fail-under=75 --omit='.venv/*,.tox/*' --show-missing
+       ${PYTHON} -m coverage run -m authbox.tests $(TESTOPTS)
+       ${PYTHON} -m coverage report --fail-under=75 --omit='authbox/tests/*' --include='authbox/*' --show-missing
 
 .PHONY: format
 format:
-       python -m isort --recursive -y $(SOURCES)
-       python -m black $(SOURCES)
+       ${PYTHON} -m isort --recursive -y $(SOURCES)
+       ${PYTHON} -m black $(SOURCES)
 
 .PHONY: lint
 lint:
-       python -m isort --recursive --diff $(SOURCES)
-       python -m black --check $(SOURCES)
-       python -m flake8 $(SOURCES)
+       ${PYTHON} -m isort --recursive --diff $(SOURCES)
+       ${PYTHON} -m black --check $(SOURCES)
+       ${PYTHON} -m flake8 $(SOURCES)
```

**Comment by precision** [comment]
@thvortex I just did a fresh install of Rasbian Buster Lite (2019-09-26) and after an `apt-get update && apt-get dist-upgrade && apt-get install python3-numpy` libatlas-base-dev is still not installed.

Ideally someone with a fresh Raspbian install would be able to `git clone  && cd software && make test` and have it just work.  If this Makefile is meant just for GH Actions (which I'm fine with), then I'd rather see it renamed to Makefile.github or something just to avoid confusion.

**Comment by precision** [comment]
@thatch I think I have a [Makefile](https://github.com/precision/makerspace-auth/blob/master/software/Makefile) in my fork that works how I think it should as well as not breaking GH actions.  Can you take a peek?

**Comment by thvortex** [comment]
One other change that I think is worth making: In `authbox/__init__.py` we have logic to replace RPi.GPIO on the import path with a fake if the real one is missing. But if you try running unit tests outside of venv, on Raspbian, and with Python2, then the real GPIO is already installed by default and it prevents unit tests from working.

Now that tests are in their own module, I think `authbox/tests/__init__.py` should instead do the fake RPi.GPIO replacement unconditionally.

A higher level design question though is how do we want to handle this kind of dependency injection going forward? We're doing it globally for GPIO, but via `__init__() `for fake queue/timer. We could also have each unit test patch the module under test.

**Pull request merged**
